# Generated by Django 3.0.5 on 2024-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='licence',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
