# Generated by Django 3.0.5 on 2024-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_doctor_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='licence',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
